version: '3'

services:
  express:
    build:
      context: ./Express
    volumes:
      - ./Express:/usr/app/Express
    ports:
      - "3000:3000"
  db:
    image: mongo
    container_name: "database"
    restart: always
    volumes:
      - dbdata:/data/db
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  dbdata: